name: alhuruf
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  management:
    git:
      url: https://github.com/imnadev/management.git
      ref: e3d70569296d3191c4485cb747bc88621c7a99ab

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  get_it: ^8.0.3
  injectable: ^2.5.0
  auto_route: ^9.2.2
  easy_localization_generator: ^0.3.3
  easy_localization_loader: ^2.0.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  alice: ^1.0.0-dev.12
  logger: ^2.5.0
  rx_shared_preferences: ^4.0.0
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  alice_dio: ^1.0.6
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.1.0
  keyboard_dismisser: ^3.0.0
  pocketbase: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  auto_route_generator: ^9.2.2
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.4.15
  freezed: ^3.0.4
  json_serializable: ^6.9.4

dependency_overrides:
  intl: ^0.20.2
  source_gen: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/localization/
    - assets/icons/

flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true
    lottie: true